package it.esperimenti;

public class Testo
{

    public static final String STRINGA_DIVINA_COMMEDIA = "Nel mezzo del cammin di nostra vita               \n"
                                                         + "mi ritrovai per una selva oscura,                \n"
                                                         + "ché la diritta via era smarrita. 3               \n"
                                                         + "Ahi quanto a dir qual era è cosa dura            \n"
                                                         + "esta selva selvaggia e aspra e forte             \n"
                                                         + "che nel pensier rinova la paura! 6               \n"
                                                         + "Tant’è amara che poco è più morte;               \n"
                                                         + "ma per trattar del ben ch’i’ vi trovai,          \n"
                                                         + "dirò de l’altre cose ch’i’ v’ ho scorte. 9       \n"
                                                         + "Io non so ben ridir com’i’ v’intrai,             \n"
                                                         + "tant’era pien di sonno a quel punto              \n"
                                                         + "che la verace via abbandonai. 12                 \n"
                                                         + "Ma poi ch’i’ fui al piè d’un colle giunto,       \n"
                                                         + "là dove terminava quella valle                   \n"
                                                         + "che m’avea di paura il cor compunto, 15          \n"
                                                         + "guardai in alto e vidi le sue spalle             \n"
                                                         + "vestite già de’ raggi del pianeta                \n"
                                                         + "che mena dritto altrui per ogne calle. 18        \n"
                                                         + "Allor fu la paura un poco queta,                 \n"
                                                         + "che nel lago del cor m’era durata                \n"
                                                         + "la notte ch’i’ passai con tanta pieta. 21        \n"
                                                         + "E come quei che con lena affannata,              \n"
                                                         + "uscito fuor del pelago a la riva,                \n"
                                                         + "si volge a l’acqua perigliosa e guata, 24        \n"
                                                         + "così l’animo mio, ch’ancor fuggiva,              \n"
                                                         + "si volse a retro a rimirar lo passo              \n"
                                                         + "che non lasciò già mai persona viva. 27          \n"
                                                         + "Poi ch’èi posato un poco il corpo lasso,         \n"
                                                         + "ripresi via per la piaggia diserta,              \n"
                                                         + "sì che ’l piè fermo sempre era ’l più basso. 30  \n"
                                                         + "Ed ecco, quasi al cominciar de l'erta,           \n"
                                                         + "una lonza leggera e presta molto,                \n"
                                                         + "che di pel macolato era coverta; 33              \n"
                                                         + "e non mi si partia dinanzi al volto,             \n"
                                                         + "anzi ’mpediva tanto il mio cammino,              \n"
                                                         + "ch’i’ fui per ritornar più volte vòlto. 36       \n"
                                                         + "Temp’era dal principio del mattino,              \n"
                                                         + "e ’l sol montava ’n sù con quelle stelle         \n"
                                                         + "ch’eran con lui quando l’amor divino 39          \n"
                                                         + "mosse di prima quelle cose belle;                \n"
                                                         + "sì ch’a bene sperar m’era cagione                \n"
                                                         + "di quella fiera a la gaetta pelle 42             \n"
                                                         + "l’ora del tempo e la dolce stagione;             \n"
                                                         + "ma non sì che paura non mi desse                 \n"
                                                         + "la vista che m'apparve d'un leone.               \n";

}
